# Issue 202504070005

## Code

- git hash: a3e1ab28
- branch: cmaes-discrete

## Error Message

```commandline
Traceback (most recent call last):
  File "C:\Users\csilab\Workspace\ICAP\scheme\cmaes_discrete\src\main.py", line 31, in <module>
    main()
  File "C:\Users\csilab\Workspace\ICAP\scheme\cmaes_discrete\src\main.py", line 27, in main
    analysis.plot_loss(settings, dump, save_dir)
  File "C:\Users\csilab\Workspace\ICAP\scheme\cmaes_discrete\src\analysis.py", line 13, in plot_loss
    loss_r = np.zeros(len(dump.robot_pos))
                          ^^^^^^^^^^^^^^
AttributeError: type object 'Dump' has no attribute 'robot_pos'
```

## Note

This error occurred after the record function finished.